version: "3"
services:
  # TODO: node
  # TODO: app
  todoistdb:
    image: mariadb:latest
    container_name: todoistdb
    hostname: localhost
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MARIADB_DATABASE: "todoist"
    volumes:
      - maria-data:/data/db

volumes:
  maria-data:
    external: false
