version: "3"
services:
  ui:
    container_name: ui
    build:
      dockerfile: ./todoist-ui/Dockerfile
      context: .
      target: production
    volumes:
      # Mount the container's node-modules so that it live-reload
      # can also monitor it
      - /usr/src/api/node_modules
      # Mount the todoist-server directory to monitor for file changes
      # (useful in live-reload/hot-reload)
      - ./todoist-ui:/usr/src/ui
    ports:
      - 80:80
    depends_on:
      - api

  api:
    container_name: api
    build:
      # Target the nested Dockerfile in todoist-server folder
      dockerfile: ./todoist-server/Dockerfile
      context: .
      # Build production stage from ./todoist-server/Dockerfile
      target: production
    ports:
      - 5000:5000
    # Run api container
    command: npm run start:prod
    depends_on:
      - todoistdb

  todoistdb:
    image: mariadb:latest
    container_name: todoistdb
    hostname: localhost
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MARIADB_DATABASE: "todoist"
    volumes:
      - maria-data:/data/db

volumes:
  maria-data:
    external: false
